import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const template = await readFile(path.join(root, 'src/resume.template.html'), 'utf8');
const content = JSON.parse(await readFile(path.join(root, 'src/resume.content.json'), 'utf8'));
for (const [key, entry] of Object.entries(content)) {
  if (!entry.ko?.trim() || !entry.en?.trim()) throw new Error(`Missing translation: ${key}`);
}
let output = template.replace(/\{\{([\w-]+)\}\}/g, (_, key) => {
  if (!content[key]) throw new Error(`Unknown content key: ${key}`);
  return content[key].ko;
});
const contentScript = '// Generated from the single resume content catalog.\nwindow.ResumeContent = ' + JSON.stringify(content) + ';\n';
const versions = {};
for (const filename of ['content.js', 'locale.js', 'resume.js', 'effects.js', 'resume.css']) {
  const bytes = filename === 'content.js' ? contentScript : await readFile(path.join(root, 'assets', filename));
  versions[filename] = createHash('sha256').update(bytes).digest('hex').slice(0, 12);
  output = output.replaceAll(`"./assets/${filename}"`, `"./assets/${filename}?v=${versions[filename]}"`);
}
for (const filename of ['theme-reel.mp4']) {
  const bytes = await readFile(path.join(root, 'img', filename));
  const version = createHash('sha256').update(bytes).digest('hex').slice(0, 12);
  const source = `./img/${filename}`;
  output = output.replaceAll(`"${source}"`, `"${source}?v=${version}"`);
}
await mkdir(path.join(root, 'assets'), { recursive: true });
await writeFile(path.join(root, 'index.html'), '<!-- Generated by scripts/build.mjs. Edit src/resume.content.json and src/resume.template.html. -->\n' + output);
await writeFile(path.join(root, 'assets/content.js'), contentScript);
for (const [folder, locale] of [['kr', 'ko'], ['en', 'en']]) {
  await writeFile(path.join(root, folder, 'index.html'), `<!doctype html>
<html lang="${locale}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Minwoo Kim | Resume</title>
  <link rel="canonical" href="https://minwoo19930301.github.io/resume/">
  <script src="../assets/locale.js?v=${versions['locale.js']}"></script>
</head>
<body>
  <p><a href="../?lang=${locale}">${locale === 'ko' ? '김민우 이력서로 이동' : 'Continue to Minwoo Kim’s resume'}</a></p>
  <script>location.replace(ResumeLocale.legacyURL(location.href, '${locale}'));</script>
</body>
</html>
`);
}
console.log(`Built one resume with ${Object.keys(content).length} bilingual entries and two legacy aliases.`);
